-- Add migration script here

-- Create Words Table
CREATE TABLE words(
                      id            INT         GENERATED BY DEFAULT AS IDENTITY ,
                      PRIMARY KEY (id),
                      word         TEXT        NOT NULL UNIQUE
);